services:
  therapyfill:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ${PWD}/db.sqlite
        target: /data/db.sqlite
    environment:
      - COMPATABILITY_DATE=${COMPATABILITY_DATE}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_ENCRYPTION_KEY=${DATABASE_ENCRYPTION_KEY}
      - SESSION_SECRET=${SESSION_SECRET}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - VITE_TWILIO_PHONE_NUMBER=${VITE_TWILIO_PHONE_NUMBER}
      - VITE_GOOGLE_VOICE_PHONE_NUMBER=${VITE_GOOGLE_VOICE_PHONE_NUMBER}
      - LOG_HASH_KEY=${LOG_HASH_KEY}
  posthog:
    image: posthog/posthog:latest
    container_name: posthog
    depends_on:
      - postgres
      - redis
      - clickhouse
    environment:
      DATABASE_URL: postgres://posthog:posthogpassword@postgres:5432/posthog
      REDIS_URL: redis://redis:6379
      CLICKHOUSE_DATABASE_URL: http://clickhouse:8123
      SITE_URL: https://yourdomain.com/posthog
      SECRET_KEY: a-secure-key
    restart: always
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: posthog
      POSTGRES_PASSWORD: posthogpassword
      POSTGRES_DB: posthog
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:6
    container_name: redis
    restart: always

  clickhouse:
    image: clickhouse/clickhouse-server:22.3
    container_name: clickhouse
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    restart: always

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - therapyfill
      - posthog
    restart: always

  volumes:
    postgres_data:
    clickhouse_data:
    caddy_data:
    caddy_config:
